tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mas-cli/tap"
tap "quackduck/tap"

brew "ansiweather"
brew "archey"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "boxes"
brew "brew-cask-completion"
brew "cmake"
brew "coreutils"
brew "curl"
brew "dialog"
brew "dos2unix"
brew "findutils"
brew "fortune"
brew "gcc"
brew "git"
brew "git-lfs"
brew "git-open"
brew "glib"
brew "gnu-sed"
brew "gnupg"
brew "highlight"
brew "hugo"
brew "iproute2mac"
brew "liquidprompt"
brew "mas"
brew "moreutils"
brew "pcre"
brew "php"
brew "qt"
brew "shellcheck"
brew "sl"
brew "smartmontools"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "tree"
brew "wget"

cask "1password6"
cask "a-better-finder-rename"
cask "alfred"
cask "avidemux"
cask "calibre"
cask "epubquicklook"
cask "firefox-esr"
cask "google-earth-pro"
cask "imazing"
cask "iterm2"
cask "kindle"
cask "macjournal"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlplayground"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicknfo"
cask "setapp"
cask "sublime-text"
cask "sublime-merge"
cask "temurin11"
cask "thunderbird"
cask "suspicious-package"
cask "ttscoff-mmd-quicklook"
cask "virtualbox"
cask "vlc"
cask "webpquicklook"
cask "whatroute"
cask "xquartz"

mas "Parcel", id: 639968404
mas "My Medical", id: 489690915
mas "BitdefenderVirusScanner", id: 500154009
mas "CarMaintenance", id: 413628447
mas "Speedtest", id: 1153157709
mas "CHM Reader", id: 424182884
mas "PopClip", id: 445189367
