#
# Sample configuration file for the Samba suite for Debian GNU/Linux.
#
#
# This is the main Samba configuration file. You should read the
# smb.conf(5) manual page in order to understand the options listed
# here. Samba has a huge number of configurable options most of which
# are not shown in this example
#
# Some options that are often worth tuning have been included as
# commented-out examples in this file.
#  - When such options are commented with ";", the proposed setting
#    differs from the default Samba behaviour
#  - When commented with "#", the proposed setting is the default
#    behaviour of Samba but the option is considered important
#    enough to be mentioned here
#
# NOTE: Whenever you modify this file you should run the command
# "testparm" to check that you have not made any basic syntactic
# errors.

#======================= Global Settings =======================

[global]
  dns proxy = no
  server role = standalone server
  syslog = 0
  workgroup = RickNET
  panic action = /usr/share/samba/panic-action %d
  map to guest = bad user
  log file = /var/log/samba/log.%m
  passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
  passwd program = /usr/bin/passwd %u
  unix password sync = yes
  passdb backend = tdbsam
  max log size = 1000
  os level = 20
  obey pam restrictions = yes
  pam password change = yes

#======================= Share Definitions =======================

[transfer]
  comment = transfer
  browseable = no
  path = /transfer
  writeable = yes
  create mask = 0660
  directory mask = 0770
  force user = root
  force group = root
