[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=
RebootCommand=

[Theme]
Current=debian-maui
CursorTheme=Adwaita

[Users]
HideUsers=_apt,avahi,backup,bin,daemon,dnsmasq,games,geoclue,gnats,irc,list,lp,mail,man,messagebus,news,nobody,proxy,pulse,rtkit,sddm,speech-dispatcher,sshd,sync,sys,systemd-coredump,systemd-network,systemd-resolve,systemd-timesync,tss,usbmux,uucp,vboxadd,www-data
MaximumUid=60000
MinimumUid=0
