[global]
passdb backend = smbpasswd
workgroup = RickNET
security = user
server string = nasbackup
encrypt passwords = Yes
username level = 0
map to guest = Bad User
null passwords = yes
max log size = 10
socket options = TCP_NODELAY SO_KEEPALIVE SO_SNDBUF=65536 SO_RCVBUF=65536
os level = 20
preferred master = no
dns proxy = no
guest account = guest
directory mask = 0777
create mask = 0777
oplocks = yes
locking = yes
disable spoolss = no
load printers = no
veto files = /.AppleDB/.AppleDouble/.AppleDesktop/:2eDS_Store/Network Trash Folder/Temporary Items/TheVolumeSettingsFolder/.@__thumb/.@__desc/:2e*/.@__qini/.Qsync/.@upload_cache/.qsync/.qsync_sn/.@qsys/.streams/.digest/
delete veto files = yes
map archive = no
map system = no
map hidden = no
map read only = no
deadtime = 10
use sendfile = yes
unix extensions = no
store dos attributes = yes
client ntlmv2 auth = yes
dos filetime resolution = no
inherit acls = no
wide links = yes
force unknown acl user = yes
domain logons = no
case sensitive = auto
domain master = auto
local master = no
enhance acl v1 = yes
remove everyone = no
conn log = no
kernel oplocks = no
printcap cache time = 0
pid directory = /var/lock
server role = auto
smb2 leases = yes
durable handles = yes
kernel share modes = no
posix locking = no
acl allow execute always = yes
server signing = disabled
streams_depot:delete_lost = yes
streams_depot:check_valid = no
fruit:nfs_aces = no
fruit:veto_appledouble = no
winbind expand groups = 1
winbind enum groups = Yes
winbind enum users = Yes
max protocol = SMB2_10
vfs objects =  catia fruit qnap_macea streams_depot

[backups]
comment = Backup of backups dir on backupserver
path = /backups
browsable = yes
oplocks = yes
ftp write only = no
public = yes
invalid users = "guest"
read list =
write list = "admin","rtruell"
valid users = "root","admin","rtruell"
inherit permissions = yes

[data]
comment = Backup of data dir on fileserver
path = /data
browsable = yes
oplocks = yes
ftp write only = no
public = yes
invalid users = "guest"
read list =
write list = "admin","rtruell"
valid users = "root","admin","rtruell"
inherit permissions = yes
